name: Build

on: 
  #push:
    #branches:      
      # Release branches
      #- "[0-9]+.[0-9]+.X"
      
  # Manual run
  workflow_dispatch:
  
jobs: 
  build_universal_wheel:
    name: Build universal wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['3.10']
        include:
          - os: ubuntu-20.04
            arch: "x86_64"
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}     

    - name: Build sdist
      run: |              
        python -m pip install build
        python -m build --sdist --wheel .

    - name: Save sdist
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
        if-no-files-found: error
        
               
