name: Build

on: 
  push:
    branches:      
      - deploy-pypi-test
      - deploy-pypi
      
jobs: 
  build_wheel:
    name: Build Python 3 wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['3.10']
        include:
          - os: ubuntu-20.04
            arch: "x86_64"
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}     

    - name: Build wheel
      run: |              
        python -m pip install build
        python -m build --wheel .

    - name: Save sdist
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
        if-no-files-found: error        
        
  upload_pypi_test:
    name: Upload to PyPI test
    needs: [build_wheel]
    runs-on: ubuntu-latest    
    environment: 
      name: pypi
      url: https://test.pypi.org/p/interbasepython
    permissions:
      id-token: write
    # upload to PyPI test only for pushes to 'deploy-pypi-test' 
    if: github.event_name == 'push' && github.ref == 'refs/heads/deploy-pypi-test'    
    steps:                       
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
          
      - name: Publish package to TestPyPI      
        uses: pypa/gh-action-pypi-publish@master
        with:
          repository_url: https://test.pypi.org/legacy/    
          
  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheel]
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/p/interbasepython
    permissions:
      id-token: write
    # upload to PyPI only for pushes to 'deploy-pypi' 
    if: github.event_name == 'push' && github.ref == 'refs/heads/deploy-pypi'
    steps:                       
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
          
      - name: Publish package to PyPI      
        uses: pypa/gh-action-pypi-publish@master 
